update dependency in test project
- use Scala 2.11
- use latest version unfiltered (0.9.1)
- s/scala.annotation.target.field/scala.annotation.meta.field https://github.com/scala/scala/commit/4e86106b5b0637aa88de2e3d5a8751d918e4c069
- use Plan instead of Planify (compile error)

```
sbt-appengine/src/sbt-test/sbt-appengine/simple/src/main/scala/echofilter.scala:8: Implementation restriction: <$anon: unfiltered.request.HttpRequest[javax.servlet.http.HttpServletRequest] => unfiltered.response.ResponseFunction[javax.servlet.http.HttpServletResponse]> requires premature access to class EchoFilter.
[error] class EchoFilter extends unfiltered.filter.Planify ({
[error]                                                     ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```